return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "c",
      "comment",
      "cpp",
      "css",
      "dockerfile",
      "fish",
      "go",
      "graphql",
      "html",
      "javascript",
      "json",
      "jsonc",
      "lua",
      "python",
      "regex",
      "rust",
      "scss",
      "toml",
      "tsx",
      "typescript",
      "yaml",
      "gdscript",
      "gdshader",
      "godot_resource",
    },
  },
}
